from django.urls import path

from cafe.views import (
    IndexView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookYearUpdateView,
    CookDeleteView,
    ToggleAssignToDishView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dishtypes/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dishtypes/create/", DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dishtypes/<int:pk>/update/", DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dishtypes/<int:pk>/delete/", DishTypeDeleteView.as_view(),
         name="dish-type-delete"),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/create/", IngredientCreateView.as_view(),
         name="ingredient-create"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(),
         name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(),
         name="ingredient-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(),
         name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(),
         name="dish-delete"),
    path("dishes/<int:pk>/toggle-assign/", ToggleAssignToDishView.as_view(),
         name="toggle-dish-assign", ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookYearUpdateView.as_view(),
         name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(),
         name="cook-delete"),
]

app_name = "cafe"
